### ISSUE TITLE
[VT-86] Outdated Repository URL, Missing Project Summary Web Site

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#108]
_Benjamin Weber on 2014-05-13T18:14:47Z says:_

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-05-13T18:14:47Z
Modified: 2015-03-02T04:36:35Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-03-02T04:36:35Z says:_ 

 Everything in here has been address. Thank you Benjamin!

**Comment by pbeckingham** [comment]
[VT-86_0001-Updated-vit-git-URL.patch.txt](https://github.com/scottkosty/vit/files/1755281/VT-86_0001-Updated-vit-git-URL.patch.txt)
