### ISSUE TITLE
[VT-96] [Patch] Makefile.in patch

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#118]
_Ankur Sinha on 2014-06-24T04:03:20Z says:_ 

 A patch that corrects a few things in the Makefile.in
*  removes the use of sudo from the install target
*  place configuration to /etc/ instead of /user/etc/
*  place man pages in /usr/share/man/* instead of /usr/man/*

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-24T04:03:20Z
Modified: 2014-06-27T01:05:12Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2014-06-25T19:46:48Z says:_ 

 Fixed at e713a2c3 and c9cf4778 on the 1.3 branch. Thanks Ankur.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2014-06-27T01:05:12Z says:_ 

 Note the change to access the config file also:

diff --git a/vit.pl b/vit.pl
* our $commands_file = '%prefix%/etc/vit-commands';
+our $commands_file = '/etc/vit-commands';

**Comment by pbeckingham** [comment]
[VT-96_vit-1.2-Makefile.patch.txt](https://github.com/scottkosty/vit/files/1755279/VT-96_vit-1.2-Makefile.patch.txt)
