### ISSUE TITLE
[VT-107] Fatal error: ... must print an "ID" column

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#128]
_Klaus Baumgarten on 2014-12-09T12:13:39Z says:_ 

 vit is great! Thank you.

``Fatal error: default.command ("next") must print an "ID" column``

Seems like I'm not the only one having this problem:

https://aur.archlinux.org/packages/vit/ (comment by adb)

Is there any fix?

Thanks so much for your work on this project!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-12-09T12:13:39Z
Modified: 2015-01-09T15:54:53Z
```

**Comment by taskwarrior** [comment]
_PeterN on 2015-01-09T07:54:20Z says:_ 

 This is often caused by vit having (hard?)coded paths to "vit-commands" and "task" ($commands_file and $vit), or a mistake in the provided command line argument. Simply when $task execution fails. Some of immediate remedies for fixing this would be to check lines vit:14-15 in the executed script and see whether they point to right paths.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-01-09T15:54:53Z says:_ 

 See also:
https://bug.tasktools.org/browse/VT-15
https://bug.tasktools.org/browse/VT-18

**Comment by ifohancroft** [comment]
I can also confirm this bug on Fedora 29, with vit and taskwarrior installed from the repos.
Vit version 1.3.beta1
TaskWarrior version 2.5.1

The bug happens when there are not tasks.

**Comment by ifohancroft** [comment]
Is there a fix for this?

**Comment by scottkosty** [comment]
@ifohancroft can you try the 2.x branch?

**Comment by ifohancroft** [comment]
@scottkosty Yes. This is fixed in the 2.x branch. Thank you very much!

**Comment by scottkosty** [comment]
@ifohancroft great! Thanks for testing. Chad's impressive rewrite of VIT has fixed some annoying bugs (like this one) along the way.
