### ISSUE TITLE
[VT-115] Context support in vit

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#136]
_David Patrick on 2015-02-25T04:25:28Z says:_ 

 Now that task has a function to filter by context (as of unreleased version 2.4.2) vit should have built-in support for the feature. 

For starters. a key-mapping " map @=:!wr task context" (in .vitrc) goes a long way, but tab-completion using the (new) _context helper-command, would be good.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-02-25T04:25:28Z
Modified: 2015-07-28T21:39:26Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2015-07-28T21:38:14Z says:_ 

 Related to context support; it's easy to change context with vit, but there's now visual feedback to indicate which, if any, context filter is in use.

Something like adding context (if any) to the title bar, would do it.

**Comment by lenalebt** [comment]
I installed the latest development snapshot and do see the visual feedback in the title bar about the context I am in currently. However, the filters applied to the context do not seem to be used at all?

I have three contexts, and the applied filters do filter out all the other tasks. My main contexts are "work" and "home", and I'd like to keep them separate. Context switching and showing using taskwarrior CLI works as expected, but not in vit.

Am I missing something?

**Comment by thehunmonkgroup** [comment]
VIT 2.x pulls data directly from the TaskWarrior database via the export command, and I expected that command to respect the set context, which it does not.

This means the needed fix will require manually parsing the context filters, storing them, and silently applying them to all commands, which may not be a simple fix. I'll see what I can do.

**Comment by thehunmonkgroup** [comment]
The fix turned out to be fairly easy: https://github.com/scottkosty/vit/commit/fff7c1dff35746faeb0e6b2c29bcb1a93682c257

@lenalebt I'm going to wait a bit longer before rolling the next beta, but if you'd like to test this fix you should be able to install the latest code by uninstalling the previous beta version, then installing from the git 2.x branch:

```
pip uninstall vit
pip install git+https://github.com/scottkosty/vit.git@2.x
```

Let me know if that corrects the issue for you.

**Comment by thehunmonkgroup** [comment]
I decided to finish this issue off and add a built in action for switching context, mapped to the 'c' key by default.

This opens the command bar, allowing you enter a context directly, and includes tab completion for all contexts and the 'none' keyword. The command respects the global 'wait' config setting.

Note that contexts are only updated on application start, or when the global refresh action is initiated (mapped to Ctrl+l by default).

**Comment by lenalebt** [comment]
Wow, *that* was fast :D.

Yes, it's fixed now, just tried it. Nice work, thank you!

Edit: I installed from source, is that any different? I'm not a python person.
