### ISSUE TITLE
[VT-116] Add support for KEY_HOME and KEY_END (Patch)

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#137]
_Jochen Sprickerhof on 2015-03-03T10:47:44Z says:_ 

 Title says all.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-03-03T10:47:44Z
Modified: 2015-03-04T05:54:52Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-03-04T05:54:37Z says:_ 

 Good idea. We already have code that does the same thing but for different keys, so I just added KEY_HOME and KEY_END on to the if condition. I also added support for those keys when inside a prompt (to go to the beginning and end). Also, I added an entry to the change log and wrote a more detailed commit message. It's in at 6e70c858.

Thanks!

**Comment by pbeckingham** [comment]
[VT-116_0001-Add-support-for-KEY_HOME-and-KEY_END.patch.txt](https://github.com/scottkosty/vit/files/1755274/VT-116_0001-Add-support-for-KEY_HOME-and-KEY_END.patch.txt)
