### ISSUE TITLE
annotating recurring tasks vs. annotating their instances

### ISSUE THREAD

**Issue by Ri-Ga** [scottkosty/vit#16]
In current vit, default mode for adding annotations is to annotate the recurring task itself. In my work with vit/taskwarrior so far, I found annotating the **instances** of recurring tasks more natural.

I have implemented a simple patch for vit (essentially just making the default answer in `task_exec` parametric) but wanted to discuss first before making a pull request.

- Do you have the same preference as I?
- Do you possibly prefer being able to choose what to annotate (and denotate) each time individually?

**Comment by scottkosty** [comment]
> Do you have the same preference as I?

I think I do. We should poll some other VIT users. What I do is I have a shortcut that takes me to the parent task so if I want to edit the parent task I just use that.

> Do you possibly prefer being able to choose what to annotate (and denotate) each time individually?

I personally don't, but this might be the best default behavior for VIT since in a quick test I think this is what Taskwarrior does, right?

**Comment by scottkosty** [comment]
> What do you think about vit's default behavior

My first reaction is that VIT's default behavior should be whatever taskwarrior's default behavior is.

**Comment by Ri-Ga** [comment]
>> Do you possibly prefer being able to choose what to annotate (and denotate) each time individually?

> I personally don't, but this might be the best default behavior for VIT since in a quick test I think this is what Taskwarrior does, right?

Yes, taskwarrior seems to always ask and it seems like there is no taskrc option for changing this default. I personally would not like to be asked each time in vit, but I do acknowledge that others might prefer a different default or no default.

So, what about adding vitrc configuration elements such as

    set default.annotate.task=("recurring" | "instance" | "ask")
    set default.delete.task=("recurring" | "instance" | "ask")

? The result of your polling would still be relevant when the configuration elements are added, since they could determine the default behavior of vit.

**Comment by scottkosty** [comment]
I think it would be better to make a request to Taskwarrior to create a new config variable. In fact, I believe the next major Taskwarrior version is centered around improvements in recurrence (sources: https://taskwarrior.org/news/news.20170401.html and https://taskwarrior.org/docs/history.html), so now might be a good time.

If the request to Taskwarrior itself is denied for some reason that is not relevant to VIT, then we could consider a workaround. But right now I don't see what that reason would be.

Further, patching "upstream" (a config variable to Taskwarrior) would spread the benefit to more users (who might also want to use the new config variable).

When you make the feature request at https://bug.tasktools.org/, select the "recurrence" component. I checked the list of bugs/requests with the recurrence component set (https://bug.tasktools.org/issues/?jql=project+%3D+TW+AND+component+%3D+Core%3ARecurrence) and did not see such a request yet.

**Comment by Ri-Ga** [comment]
I followed your suggestion. The feature request can be found at [https://bug.tasktools.org/browse/TW-1916](https://bug.tasktools.org/browse/TW-1916)

**Comment by scottkosty** [comment]
Great, thanks for doing that! Let's close this issue for now. If we change our minds and decide that this functionality does belong in VIT, we can reopen.
