### ISSUE TITLE
Ability to modify waiting state of a task

### ISSUE THREAD

**Issue by danihodovic** [scottkosty/vit#160]
Is it possible to wait or unwait a task in vit?

**Comment by scottkosty** [comment]
@danihodovic this will be implemented in 1.3. See #3. You can try 1.3.beta1, which I consider to be very stable.

**Comment by danihodovic** [comment]
Thanks @scottkosty . `:Wait` works, but is it possible to remove the wait for a task, e.g set `wait:`?

**Comment by scottkosty** [comment]
@danihodovic I think the only current way is to press "m" for modify and then manually type "wait:<return>". I wonder if pressing "w<return>" should remove it. Currently that is just a "no-op". I'm not sure what the user expects in this situation.

**Comment by thehunmonkgroup** [comment]
@danihodovic VIT 2.x alpha 1 has been released, and the wait functionality operates as you expect there:

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by danihodovic** [comment]
Thanks @thehunmonkgroup

**Comment by scottkosty** [comment]
@danihodovic if you happen to give 2.x alpha 1 a test, let us know how it goes! We would be very interested in your feedback.

**Comment by danihodovic** [comment]
I've started using it. The docs about configuration and key bindings is easier to understand this time around :+1: Thanks for the release

**Comment by scottkosty** [comment]
> The docs about configuration and key bindings is easier to understand this time around

@danihodovic that's great to hear! All credit for the release goes to @thehunmonkgroup. All blame for the last time around goes to me :)
