### ISSUE TITLE
"Start" a task keybinding is missing

### ISSUE THREAD

**Issue by maikeldotuk** [scottkosty/vit#168]
I can't find the key binding for starting a task so I end up using vit with another window with the heavy ptask to just start a task. 

I have read the manual and I can't find that keybinding, either it is missing or is undocumented. Please help

**Comment by scottkosty** [comment]
@maikeldotuk are you using the 1.3 branch of Vit (1.3 has not yet been released yet so that is why it's not on master)? With Vit 1.3dev, you can do ":help" and that takes you to the shortcuts. From there it shows that "b" is used to start/stop. I hope to get around to releasing 1.3 soon. I consider it very stable.

**Comment by maikeldotuk** [comment]
Tried with my version (btw, there's no vit --help nor vit --version, it could do with one)
and I couldn't get it to work. 

I'm using Manjaro, an Arch-based distro. So I changed from Vit (saw in Pamac that it was the 1.2) to vit-git, which if I'm not wrong it takes the latest from this repo directly. 

And now it works. Yaaaaaaaaaayyy!
Thank you for pointing me in the right direction.

**Comment by maikeldotuk** [comment]
I've got another issue but I'll create a new one for that, it's based in this one

**Comment by scottkosty** [comment]
@maikeldotuk glad it works for your now.

> btw, there's no vit --help nor vit --version, it could do with one

This should work with 1.3dev.

**Comment by maikeldotuk** [comment]
You're correct. In versión 1.3 it does exist. On 8 Mar 2019 02:53, Scott Kostyshak <notifications@github.com> wrote:@maikeldotuk glad it works for your now.

btw, there's no vit --help nor vit --version, it could do with one

This should work with 1.3dev.
