### ISSUE TITLE
Feature request... add tag

### ISSUE THREAD

**Issue by mstankus** [scottkosty/vit#22]
I did not see a way to add tags to tasks using vit.
It would be great if you could implement this.

**Comment by scottkosty** [comment]
It is implemented in the 1.3 branch (still in development). It is bound to the key "T". Please let me know if you test 1.3 and what you think of the tag feature.

**Comment by fdela** [comment]
This issue can be closed

**Comment by scottkosty** [comment]
@fdela thanks for your help with going through the issues!
