### ISSUE TITLE
[VT-11] Vit: tab completion of report can get confused

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#33]
_Scott Kostyshak on 2013-04-07T00:06:43Z says:_ 

 To reproduce:

1. start Vit
2. enter ":"
3. type "minim<tab>"
("minimal" should now be written)
4. use backspace to delete "minimal"
5. type "complet<tab>"
6. "all" is shown for me (where I expected "completed").

Note that "complet<tab>" correctly expands to "completed" if it's the first completion I try.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-07T00:06:43Z
Modified: 2014-02-09T01:16:50Z
```

**Comment by thehunmonkgroup** [comment]
VIT 2.x alpha 1 has been released, think you can investigate if this issue still occurs there?

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by fdela** [comment]
I don't have this issue with 2.0.0
