### ISSUE TITLE
[VT-14] "Enter" does not work for tasks with no ID

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#36]
_Scott Kostyshak on 2013-09-16T20:19:27Z says:_ 

 Using UUIDs globally would solve this, but there might be an easy fix for using using UUIDs locally here.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-09-16T20:19:27Z
Modified: 2014-02-09T01:16:50Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-09-17T05:53:11Z says:_ 

 Good idea from djp: until we have a long-term solution, we should at least give an error.

**Comment by thehunmonkgroup** [comment]
VIT 2.x alpha 1 has been released, all tasks are operated on by uuid:

https://github.com/scottkosty/vit/releases/tag/v2.0.0a1

**Comment by fdela** [comment]
Using v2.0.0, works correctly, so this issue can be closed

**Comment by scottkosty** [comment]
> Using v2.0.0, works correctly, so this issue can be closed

Thanks!
