### ISSUE TITLE
[Feature suggestion] Add a .vitrc variable to supress the confirmation shown after modifying and adding tasks

### ISSUE THREAD

**Issue by joelostblom** [scottkosty/vit#7]
First, thanks for maintaining VIT! It is the best interface to taskwarrior that I have come across so far, and it really facilitates working with my tasks!

Whenever I add or modify a task in VIT, the shell pops up a message with info about the task and I need to press Enter to return back to VIT. I tried setting `verbose=nothing` in my `~/taskrc`, which removes the task information in the message, but still shows an empty message with one line prompting me to press return to continue.

Is there a way around this so that I just have to press return once when creating the task and stay in VIT, instead of seeing the message screen and having to press return to go back into VIT?

---

**Update 20170308** I initially forgot to mention that I have remapped task addition as such `map a=:!rw task add project:Work `, to save myself typing in the project every time. The default task addition binding does not require confirmation.

**Comment by scottkosty** [comment]
You could put something like the following in you `~/.vitrc` file:

`map m=:!r task %TASKID modify $(read -p "Modify: " MODIFICATION; echo $MODIFICATION)<Return>`

I tested on the 1.3 branch and this works for me.

For more information, see `man vitrc`.

**Comment by joelostblom** [comment]
Great thanks! That works well on 1.2-2 also. Is it possible to have the "modify" show up in the VIT statusbar (where the preconfigured commands are displayed) rather than in a new terminal window?

**Comment by scottkosty** [comment]
That's not possible. The advantage of using the custom command is that you have complete control. The disadvantage is that you have to handle everything yourself. You might prefer something like this, which shows the task information (you can customize this using Taskwarrior commands, e.g. custom reports), and then below gives the modify prompt:

`map m=:!r task %TASKID; task %TASKID modify $(read -p "Modify: " MODIFICATION; echo $MODIFICATION)<Return>`

**Comment by joelostblom** [comment]
Cool, thank you!

**Comment by scottkosty** [comment]
Glad it does what you want. Let's keep this issue open and rephrase it as an enhancement request for a .vitrc configuration variable that controls whether the confirmation is shown or not.

**Comment by joelostblom** [comment]
Sounds good,  reworded the title accordingly, feel free to modify further.

**Comment by scottkosty** [comment]
Looks good! Thanks.

**Comment by scottkosty** [comment]
Note the cross-post at https://answers.tasktools.org/questions/5440599/how-can-i-remove-the-need-to-press-enter-after-adding-and-modifying-tasks-in-vit. (By the way, it is always useful to link between cross-posts so that if someone has the same question and finds one post by google, they can see a link to the other place the question is asked and thus find other answers.)
