### ISSUE TITLE
[VT-52] VITtk; no way to set selection fg color [patch]

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#74]
_Bryce Harrington on 2011-05-06T09:26:34Z says:_ 

 I like to invert the color scheme - black on white instead of white or green on black.  vittk provides configuration variables to do most of this, but lacks a way to set the selection bar's fg color, which makes the text it is on unreadable (black on black).

The attached patch adds a $selection_fg variable which allows setting the color of this bar.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-05-06T09:26:34Z
Modified: 2015-03-02T05:18:14Z
```

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-05-06T09:26:34Z says:_ 

 Attachment add_selection_fg.patch has been added with description: patch

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-05-06T09:47:15Z says:_ 

 Fixed up patch...  selection_fg actually accepts only 0 or 1, not an arbitrary color as I assumed with the previous patch.

**Comment by taskwarrior** [comment]
_steve rader on 2012-11-24T18:47:54Z says:_ 

 VITtk bugs have been deprecated by [[vit|Vit]].

When [[vit|Vit]] migrates to Task-native colorization, support for specifying the selection colors (both foreground and background) will be included.

**Comment by taskwarrior** [comment]
_steve rader on 2012-11-28T19:06:30Z says:_ 

 In Vit as of version 0.4 (or maybe 0.3) the selection color defaults to
white on blue but can be specified using the color.vit.selection configuration
entry.  For example, with a Gnome (light-256.theme) kinda theme, use...
<pre>
color.vit.selection=color231 on color68
</pre>

**Comment by taskwarrior** [comment]
_PeterN on 2015-01-08T22:57:48Z says:_ 

 It would be great if this was documented somewhere. I actually modified the default in my sources to implement this only to later find here that it already is implemented.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-01-08T23:32:09Z says:_ 

 Agreed. This and also the others that are parsed in init_task_env.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2015-03-02T05:18:14Z says:_ 

 Peter, can you post a patch that adds documentation for this? I don't have a good understanding of how VIT deals with colors.

**Comment by pbeckingham** [comment]
[VT-52_add_selection_fg.patch.txt](https://github.com/scottkosty/vit/files/1755284/VT-52_add_selection_fg.patch.txt)
