### ISSUE TITLE
[VT-57] VITtk; unclear how to specify font sizes

### ISSUE THREAD

**Issue by taskwarrior** [scottkosty/vit#79]
_Bryce Harrington on 2011-05-06T10:00:19Z says:_ 

 I wanted to use the Monospace font, but specifying it for font in .vittkrc resulted in a VITtk window that was too big.

The man page didn't indicate how to specify the font size, so had to experiment ("Monospace-10", "Monospace:10", etc.) until I figured it out.

Anyway, the attached patch will save future people in my shoes a few minutes...

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-05-06T10:00:19Z
Modified: 2014-02-09T02:23:41Z
```

**Comment by taskwarrior** [comment]
_steve rader on 2011-05-06T13:30:18Z says:_ 

 > The man page didn't indicate how to specify the font size, so had to experiment ("Monospace-10", "Monospace:10", etc.) until I figured it out.

Your suggestion is not portable: there are three font spec types 
that may or may not work depending on the platform.  

The portable magic for figuring out how to change the font size is eluded 
to in the FONTS section of the man page, which reads "Instructions for browsing
fixed-width fonts can be found in the /usr/local/share/doc/vittk/Fonts 
file".  I'll reword that section such that it clearly references changing
font size as well as selecting fixed-width fonts.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-05-06T16:14:40Z says:_ 

 "Instructions for browsing fixed-width fonts can be found in the /usr/local/share/doc/vittk/Fonts file".

In fact I did see that, but that file only refers to dealing with X fonts.  Monospace was not listed in xfontsel, so the advice the file gave was inaccurate and ultimately unhelpful.

**Comment by taskwarrior** [comment]
_steve rader on 2011-05-06T18:03:20Z says:_ 

 Bryce Harrington wrote:
> "Instructions for browsing fixed-width fonts can be found in the /usr/local/share/doc/vittk/Fonts file".
> 
> In fact I did see that, but that file only refers to dealing with X fonts.  Monospace was not listed in xfontsel, so the advice the file gave was inaccurate and ultimately unhelpful.

I can't envision why you've found the advice in the Fonts file inaccurate
and unhelpful.  Can you explain more? 

What you're suggesting is to steer folks to a single GTK+ font type/style.
That's rather limited advice, I'm not sure if it's portable, and it doesn't
work for me: for sizes greater than 14, I get a font type that's not "Monospace"!
(I use RHEL5.)

It would be great to provide some systematic how-to advice about using GTK+
fonts, but to my knowledge there's no stand-alone GTK+ font browser and
my experiences with guessing at GTK+ font selection widget information to
actual font name mappings has been very problematic.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-05-06T18:36:56Z says:_ 

 It doesn't matter to me; I already have my issue sorted out.  Just thought it'd be nice to document how to make the application look "normal" on Ubuntu; if that's unimportant to you feel free to disregard my patch, I won't bother you further.

**Comment by taskwarrior** [comment]
_steve rader on 2012-11-24T18:45:11Z says:_ 

 VITtk bugs have been deprecated by [[vit|Vit]].

This bug is no longer applicable in [[vit|Vit]].

To modify the font that is used by [[vit|Vit]], you must modify the font used for the terminal it's invoked in (e.g. xterm.)

**Comment by pbeckingham** [comment]
[VT-57_font-size-man.patch.txt](https://github.com/scottkosty/vit/files/1755283/VT-57_font-size-man.patch.txt)
